/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.6.0
 *
 * Project: 'core1.Debug+MCXN947' 
 * Target:  'Debug+MCXN947' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "fsl_device_registers.h"

/* NXP::CMSIS Driver:VIO:Board&FRDM-MCXN947@1.0.0 */
#define RTE_VIO_BOARD
#define RTE_VIO_FRDM_MCXN947


#endif /* RTE_COMPONENTS_H */
